data = [{'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '172',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Luke Skywalker',
  'starship': ['X-wing', 'Imperial shuttle'],
  'vehicles': ['Snowspeeder', 'Imperial Speeder Bike'],
  'weight': '77'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'n/a',
  'height': '167',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'C-3PO',
  'starship': [],
  'vehicles': [],
  'weight': '75'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'n/a',
  'height': '96',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'R2-D2',
  'starship': [],
  'vehicles': [],
  'weight': '32'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '202',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Darth Vader',
  'starship': ['TIE Advanced x1'],
  'vehicles': [],
  'weight': '136'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'Revenge of the Sith'],
  'gender': 'female',
  'height': '150',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Leia Organa',
  'starship': [],
  'vehicles': ['Imperial Speeder Bike'],
  'weight': '49'},
 {'films': ['A New Hope', 'Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '178',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Owen Lars',
  'starship': [],
  'vehicles': [],
  'weight': '120'},
 {'films': ['A New Hope', 'Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '165',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Beru Whitesun lars',
  'starship': [],
  'vehicles': [],
  'weight': '75'},
 {'films': ['A New Hope'],
  'gender': 'n/a',
  'height': '97',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'R5-D4',
  'starship': [],
  'vehicles': [],
  'weight': '32'},
 {'films': ['A New Hope'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Imperial Speeder Bike',
  'name': 'Biggs Darklighter',
  'starship': ['X-wing'],
  'vehicles': [],
  'weight': '84'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '182',
  'homeworld': 'Tribubble bongo',
  'name': 'Obi-Wan Kenobi',
  'starship': ['Jedi starfighter',
               'Trade Federation cruiser',
               'Naboo star skiff',
               'Jedi Interceptor',
               'Belbullab-22 starfighter'],
  'vehicles': ['Tribubble bongo'],
  'weight': '77'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '188',
  'homeworld': 'XJ-6 airspeeder',
  'name': 'Anakin Skywalker',
  'starship': ['Naboo fighter', 'Trade Federation cruiser', 'Jedi Interceptor'],
  'vehicles': ['Zephyr-G swoop bike', 'XJ-6 airspeeder'],
  'weight': '84'},
 {'films': ['A New Hope', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '180',
  'homeworld': 'XJ-6 airspeeder',
  'name': 'Wilhuff Tarkin',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['A New Hope',
            'The Empire Strikes Back',
            'Return of the Jedi',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '228',
  'homeworld': 'AT-ST',
  'name': 'Chewbacca',
  'starship': ['Millennium Falcon', 'Imperial shuttle'],
  'vehicles': ['AT-ST'],
  'weight': '112'},
 {'films': ['A New Hope', 'The Empire Strikes Back', 'Return of the Jedi'],
  'gender': 'male',
  'height': '180',
  'homeworld': 'AT-ST',
  'name': 'Han Solo',
  'starship': ['Millennium Falcon', 'Imperial shuttle'],
  'vehicles': [],
  'weight': '80'},
 {'films': ['A New Hope'],
  'gender': 'male',
  'height': '173',
  'homeworld': 'AT-ST',
  'name': 'Greedo',
  'starship': [],
  'vehicles': [],
  'weight': '74'},
 {'films': ['A New Hope', 'Return of the Jedi', 'The Phantom Menace'],
  'gender': 'hermaphrodite',
  'height': '175',
  'homeworld': 'AT-ST',
  'name': 'Jabba Desilijic Tiure',
  'starship': [],
  'vehicles': [],
  'weight': '1,358'},
 {'films': ['A New Hope', 'The Empire Strikes Back', 'Return of the Jedi'],
  'gender': 'male',
  'height': '170',
  'homeworld': 'Snowspeeder',
  'name': 'Wedge Antilles',
  'starship': ['X-wing'],
  'vehicles': ['Snowspeeder'],
  'weight': '77'},
 {'films': ['A New Hope'],
  'gender': 'male',
  'height': '180',
  'homeworld': 'Snowspeeder',
  'name': 'Jek Tono Porkins',
  'starship': ['X-wing'],
  'vehicles': [],
  'weight': '110'},
 {'films': ['The Empire Strikes Back',
            'Return of the Jedi',
            'The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '66',
  'homeworld': 'Snowspeeder',
  'name': 'Yoda',
  'starship': [],
  'vehicles': [],
  'weight': '17'},
 {'films': ['The Empire Strikes Back',
            'Return of the Jedi',
            'The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '170',
  'homeworld': 'Snowspeeder',
  'name': 'Palpatine',
  'starship': [],
  'vehicles': [],
  'weight': '75'},
 {'films': ['The Empire Strikes Back',
            'Return of the Jedi',
            'Attack of the Clones'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Snowspeeder',
  'name': 'Boba Fett',
  'starship': ['Slave 1'],
  'vehicles': [],
  'weight': '78.2'},
 {'films': ['The Empire Strikes Back'],
  'gender': 'none',
  'height': '200',
  'homeworld': 'Snowspeeder',
  'name': 'IG-88',
  'starship': [],
  'vehicles': [],
  'weight': '140'},
 {'films': ['The Empire Strikes Back'],
  'gender': 'male',
  'height': '190',
  'homeworld': 'Snowspeeder',
  'name': 'Bossk',
  'starship': [],
  'vehicles': [],
  'weight': '113'},
 {'films': ['The Empire Strikes Back', 'Return of the Jedi'],
  'gender': 'male',
  'height': '177',
  'homeworld': 'Snowspeeder',
  'name': 'Lando Calrissian',
  'starship': ['Millennium Falcon'],
  'vehicles': [],
  'weight': '79'},
 {'films': ['The Empire Strikes Back'],
  'gender': 'male',
  'height': '175',
  'homeworld': 'Snowspeeder',
  'name': 'Lobot',
  'starship': [],
  'vehicles': [],
  'weight': '79'},
 {'films': ['Return of the Jedi'],
  'gender': 'male',
  'height': '180',
  'homeworld': 'Snowspeeder',
  'name': 'Ackbar',
  'starship': [],
  'vehicles': [],
  'weight': '83'},
 {'films': ['Return of the Jedi'],
  'gender': 'female',
  'height': '150',
  'homeworld': 'Snowspeeder',
  'name': 'Mon Mothma',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Return of the Jedi'],
  'gender': 'male',
  'height': 'unknown',
  'homeworld': 'Snowspeeder',
  'name': 'Arvel Crynyd',
  'starship': ['A-wing'],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Return of the Jedi'],
  'gender': 'male',
  'height': '88',
  'homeworld': 'Snowspeeder',
  'name': 'Wicket Systri Warrick',
  'starship': [],
  'vehicles': [],
  'weight': '20'},
 {'films': ['Return of the Jedi'],
  'gender': 'male',
  'height': '160',
  'homeworld': 'Snowspeeder',
  'name': 'Nien Nunb',
  'starship': ['Millennium Falcon'],
  'vehicles': [],
  'weight': '68'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '193',
  'homeworld': 'Tribubble bongo',
  'name': 'Qui-Gon Jinn',
  'starship': [],
  'vehicles': ['Tribubble bongo'],
  'weight': '89'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '191',
  'homeworld': 'Tribubble bongo',
  'name': 'Nute Gunray',
  'starship': [],
  'vehicles': [],
  'weight': '90'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '170',
  'homeworld': 'Tribubble bongo',
  'name': 'Finis Valorum',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'female',
  'height': '185',
  'homeworld': 'Tribubble bongo',
  'name': 'Padmé Amidala',
  'starship': ['Naboo fighter', 'H-type Nubian yacht', 'Naboo star skiff'],
  'vehicles': [],
  'weight': '45'},
 {'films': ['The Phantom Menace', 'Attack of the Clones'],
  'gender': 'male',
  'height': '196',
  'homeworld': 'Tribubble bongo',
  'name': 'Jar Jar Binks',
  'starship': [],
  'vehicles': [],
  'weight': '66'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '224',
  'homeworld': 'Tribubble bongo',
  'name': 'Roos Tarpals',
  'starship': [],
  'vehicles': [],
  'weight': '82'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '206',
  'homeworld': 'Tribubble bongo',
  'name': 'Rugor Nass',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Tribubble bongo',
  'name': 'Ric Olié',
  'starship': ['Naboo Royal Starship'],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace', 'Attack of the Clones'],
  'gender': 'male',
  'height': '137',
  'homeworld': 'Tribubble bongo',
  'name': 'Watto',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '112',
  'homeworld': 'Tribubble bongo',
  'name': 'Sebulba',
  'starship': [],
  'vehicles': [],
  'weight': '40'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Tribubble bongo',
  'name': 'Quarsh Panaka',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace', 'Attack of the Clones'],
  'gender': 'female',
  'height': '163',
  'homeworld': 'Tribubble bongo',
  'name': 'Shmi Skywalker',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '175',
  'homeworld': 'Sith speeder',
  'name': 'Darth Maul',
  'starship': ['Scimitar'],
  'vehicles': ['Sith speeder'],
  'weight': '80'},
 {'films': ['Return of the Jedi'],
  'gender': 'male',
  'height': '180',
  'homeworld': 'Sith speeder',
  'name': 'Bib Fortuna',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'female',
  'height': '178',
  'homeworld': 'Sith speeder',
  'name': 'Ayla Secura',
  'starship': [],
  'vehicles': [],
  'weight': '55'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '79',
  'homeworld': 'Sith speeder',
  'name': 'Ratts Tyerel',
  'starship': [],
  'vehicles': [],
  'weight': '15'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '94',
  'homeworld': 'Sith speeder',
  'name': 'Dud Bolt',
  'starship': [],
  'vehicles': [],
  'weight': '45'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '122',
  'homeworld': 'Sith speeder',
  'name': 'Gasgano',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '163',
  'homeworld': 'Sith speeder',
  'name': 'Ben Quadinaros',
  'starship': [],
  'vehicles': [],
  'weight': '65'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '188',
  'homeworld': 'Sith speeder',
  'name': 'Mace Windu',
  'starship': [],
  'vehicles': [],
  'weight': '84'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '198',
  'homeworld': 'Sith speeder',
  'name': 'Ki-Adi-Mundi',
  'starship': [],
  'vehicles': [],
  'weight': '82'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '196',
  'homeworld': 'Sith speeder',
  'name': 'Kit Fisto',
  'starship': [],
  'vehicles': [],
  'weight': '87'},
 {'films': ['The Phantom Menace', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '171',
  'homeworld': 'Sith speeder',
  'name': 'Eeth Koth',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '184',
  'homeworld': 'Sith speeder',
  'name': 'Adi Gallia',
  'starship': [],
  'vehicles': [],
  'weight': '50'},
 {'films': ['The Phantom Menace', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '188',
  'homeworld': 'Sith speeder',
  'name': 'Saesee Tiin',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace'],
  'gender': 'male',
  'height': '264',
  'homeworld': 'Sith speeder',
  'name': 'Yarael Poof',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['The Phantom Menace',
            'Attack of the Clones',
            'Revenge of the Sith'],
  'gender': 'male',
  'height': '188',
  'homeworld': 'Sith speeder',
  'name': 'Plo Koon',
  'starship': ['Jedi starfighter'],
  'vehicles': [],
  'weight': '80'},
 {'films': ['The Phantom Menace', 'Attack of the Clones'],
  'gender': 'male',
  'height': '196',
  'homeworld': 'Sith speeder',
  'name': 'Mas Amedda',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '185',
  'homeworld': 'Sith speeder',
  'name': 'Gregar Typho',
  'starship': ['Naboo fighter'],
  'vehicles': [],
  'weight': '85'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '157',
  'homeworld': 'Sith speeder',
  'name': 'Cordé',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Sith speeder',
  'name': 'Cliegg Lars',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Sith speeder',
  'name': 'Poggle the Lesser',
  'starship': [],
  'vehicles': [],
  'weight': '80'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '170',
  'homeworld': 'Sith speeder',
  'name': 'Luminara Unduli',
  'starship': [],
  'vehicles': [],
  'weight': '56.2'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '166',
  'homeworld': 'Sith speeder',
  'name': 'Barriss Offee',
  'starship': [],
  'vehicles': [],
  'weight': '50'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '165',
  'homeworld': 'Sith speeder',
  'name': 'Dormé',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '193',
  'homeworld': 'Flitknot speeder',
  'name': 'Dooku',
  'starship': [],
  'vehicles': ['Flitknot speeder'],
  'weight': '80'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '191',
  'homeworld': 'Flitknot speeder',
  'name': 'Bail Prestor Organa',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '183',
  'homeworld': 'Flitknot speeder',
  'name': 'Jango Fett',
  'starship': [],
  'vehicles': [],
  'weight': '79'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '168',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Zam Wesell',
  'starship': [],
  'vehicles': ['Koro-2 Exodrive airspeeder'],
  'weight': '55'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '198',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Dexter Jettster',
  'starship': [],
  'vehicles': [],
  'weight': '102'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '229',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Lama Su',
  'starship': [],
  'vehicles': [],
  'weight': '88'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '213',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Taun We',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones'],
  'gender': 'female',
  'height': '167',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Jocasta Nu',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '96',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'R4-P17',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '193',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Wat Tambor',
  'starship': [],
  'vehicles': [],
  'weight': '48'},
 {'films': ['Attack of the Clones'],
  'gender': 'male',
  'height': '191',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'San Hill',
  'starship': [],
  'vehicles': [],
  'weight': 'unknown'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '178',
  'homeworld': 'Koro-2 Exodrive airspeeder',
  'name': 'Shaak Ti',
  'starship': [],
  'vehicles': [],
  'weight': '57'},
 {'films': ['Revenge of the Sith'],
  'gender': 'male',
  'height': '216',
  'homeworld': 'Tsmeu-6 personal wheel bike',
  'name': 'Grievous',
  'starship': ['Belbullab-22 starfighter'],
  'vehicles': ['Tsmeu-6 personal wheel bike'],
  'weight': '159'},
 {'films': ['Revenge of the Sith'],
  'gender': 'male',
  'height': '234',
  'homeworld': 'Tsmeu-6 personal wheel bike',
  'name': 'Tarfful',
  'starship': [],
  'vehicles': [],
  'weight': '136'},
 {'films': ['A New Hope', 'Revenge of the Sith'],
  'gender': 'male',
  'height': '188',
  'homeworld': 'Tsmeu-6 personal wheel bike',
  'name': 'Raymus Antilles',
  'starship': [],
  'vehicles': [],
  'weight': '79'},
 {'films': ['Attack of the Clones', 'Revenge of the Sith'],
  'gender': 'female',
  'height': '178',
  'homeworld': 'Tsmeu-6 personal wheel bike',
  'name': 'Sly Moore',
  'starship': [],
  'vehicles': [],
  'weight': '48'},
 {'films': ['Revenge of the Sith'],
  'gender': 'male',
  'height': '206',
  'homeworld': 'Tsmeu-6 personal wheel bike',
  'name': 'Tion Medon',
  'starship': [],
  'vehicles': [],
  'weight': '80'}]
